
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: coderschool.vn

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Fredrick
  # ---------------------------------------------------------------------------
  - Name: Fredrick
    Domain: fredrick.coderschool.vn
    CA:
      Hostname: ca
    Template:
      SANS:
        - "localhost"
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Alice: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Alice
    Domain: alice.coderschool.vn
    CA:
      Hostname: ca
    Template:
      SANS:
      - "localhost"
      Count: 1
    Users:
      Count: 1


  # ---------------------------------------------------------------------------
  # Bob: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Bob
    Domain: bob.coderschool.vn
    CA:
      Hostname: ca
    Template:
      SANS:
      - "localhost"
      Count: 1
    Users:
      Count: 1
